@extends('layouts.header')
@section('css')
    <link rel="stylesheet" href="{{ asset('vendors/select2/select2.min.css')}}">
    <link rel="stylesheet" href="{{ asset('vendors/select2-bootstrap-theme/select2-bootstrap.min.css')}}">
@endsection
@section('content')
	<div class="main-panel">
		<div class="content-wrapper">
            <div class='row'>
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Payrolls</h4>
                          

                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Action</th>
                                            <th>Company</th>
                                            <th>Store</th>
                                            <th>Generated By</th>
                                            <th>Cut Off</th>
                                            <th>Employee Count</th>
                                            <th>Total Basic Pay</th>
                                            <th>Contributions</th>
                                          
                                            {{-- <th>Action</th> --}}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($payrolls as $payroll)
                                    
                                            <tr>
                                                <td > 
                                                    <a title='Payroll' href='{{url("payroll/".$payroll->id)}}' target="_blank"><button type="button"  class="btn btn-inverse-danger btn-icon">
                                                    <i class="fa fa-file-pdf-o"></i>
                                                  </button></a>
                                                    <a title='Billing' href='{{url("billing/".$payroll->id)}}' target="_blank"><button type="button"  class="btn btn-inverse-success btn-icon">
                                                    <i class="fa fa-file-pdf-o"></i>
                                                  </button></a>
                                                </td>
                                                <td>{{$payroll->company}}</td>
                                                <td>{{$payroll->store}}</td>
                                                <td>{{$payroll->user->name}}</td>
                                                <td>{{date('M d, Y',strtotime($payroll->payroll_from))}} - {{date('M d, Y',strtotime($payroll->payroll_to))}}</td>
                                                <td>{{count($payroll->informations)}}</td>
                                                <td>{{number_format((($payroll->informations)->sum('basic_pay')),2)}} </td>
                                               <td><small>
                                                    SSS : {{number_format((($payroll->informations)->sum('sss_contribution')),2)}} <br>
                                                    HDMF : {{number_format((($payroll->informations)->sum('hdmf_contribution')),2)}} <br>
                                                    NHIP : {{number_format((($payroll->informations)->sum('nhip_contribution')),2)}}
                                                    </small>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
    </div>
@include('new_group')
@endsection
@section('js')
    <script src="{{ asset('vendors/select2/select2.min.js')}}"></script>
    <script src="{{ asset('js/select2.js')}}"></script>
@endsection

